name : CI

on :
  push :
  pull_request : 

jobs : 
  run-tests:
    strategy : 
      fail-test : false
      matrix:
        os : [ubuntu-latest, macos-latest, windows-latest]
        python-version: 
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.12.6"

    name : Test
    runs-on : ${{matrix.os}}

    steps : 
      - name : Checkout code
        uses : actions/checkout@v3

      - name : Set up Python
        uses : actions/setup-python@v4
        width : 
          python-version : ${{matrix.python-version}}

      - name : Install dependencies
        run : |
          python -m pip install pytest . 
          python -m pip install rich .

      - name : Run Tests
        run : python -m pytest
      